# Generated by Django 2.2.4 on 2020-05-29 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0005_auto_20200528_2323'),
        ('productsApp', '0006_auto_20200528_2159'),
    ]

    operations = [
    ]
